export const strainData = [
  // Premium Strains
  {
    id: 's1',
    type: 'strain',
    name: 'Purple Haze',
    category: 'Sativa',
    thc: '22%',
    cbd: '0.1%',
    price: 'R250/g',
    effects: ['Euphoric', 'Creative', 'Energetic'],
    flavors: ['Berry', 'Sweet', 'Earthy'],
    description: 'A legendary sativa strain known for its distinctive flavor and cerebral high.',
    images: ['/strains/purple-haze-1.jpg', '/strains/purple-haze-2.jpg'],
    rating: 4.8,
    reviews: 127,
    inStock: true
  },
  {
    id: 's2',
    type: 'strain',
    name: 'OG Kush',
    category: 'Hybrid',
    thc: '24%',
    cbd: '0.2%',
    price: 'R280/g',
    effects: ['Relaxed', 'Happy', 'Uplifted'],
    flavors: ['Pine', 'Woody', 'Peppery'],
    description: 'A potent hybrid with a perfect balance of head and body effects.',
    images: ['/strains/og-kush-1.jpg'],
    rating: 4.9,
    reviews: 245,
    inStock: true
  },
  {
    id: 's3',
    type: 'strain',
    name: 'Northern Lights',
    category: 'Indica',
    thc: '20%',
    cbd: '0.3%',
    price: 'R240/g',
    effects: ['Relaxed', 'Sleepy', 'Happy'],
    flavors: ['Sweet', 'Pine', 'Spicy'],
    description: 'A pure indica that\'s perfect for evening relaxation.',
    images: ['/strains/northern-lights-1.jpg'],
    rating: 4.7,
    reviews: 189,
    inStock: true
  },
  // Concentrates
  {
    id: 'c1',
    type: 'concentrate',
    name: 'Live Resin',
    category: 'Extract',
    potency: '82%',
    price: 'R450/g',
    consistency: 'Sugar',
    strain: 'OG Kush',
    effects: ['Potent', 'Pure', 'Clean'],
    description: 'Premium live resin extracted from fresh frozen cannabis.',
    images: ['/concentrates/live-resin-1.jpg'],
    rating: 4.9,
    reviews: 89,
    inStock: true
  },
  {
    id: 'c2',
    type: 'concentrate',
    name: 'Premium Shatter',
    category: 'Extract',
    potency: '85%',
    price: 'R500/g',
    consistency: 'Glass',
    strain: 'Durban Poison',
    effects: ['Clear', 'Strong', 'Long-lasting'],
    description: 'Glass-like consistency with high purity levels.',
    images: ['/concentrates/shatter-1.jpg'],
    rating: 4.8,
    reviews: 76,
    inStock: true
  },
  {
    id: 'c3',
    type: 'concentrate',
    name: 'Bubble Hash',
    category: 'Hash',
    potency: '65%',
    price: 'R350/g',
    consistency: 'Crumble',
    strain: 'Mixed',
    effects: ['Full Spectrum', 'Natural', 'Rich'],
    description: 'Traditional ice water hash made from premium flowers.',
    images: ['/concentrates/hash-1.jpg'],
    rating: 4.7,
    reviews: 92,
    inStock: true
  },
  // Edibles
  {
    id: 'e1',
    type: 'edible',
    name: 'Dream Gummies',
    category: 'Gummies',
    thc: '10mg/piece',
    pieces: '10',
    price: 'R180',
    flavors: ['Strawberry', 'Mango', 'Grape'],
    effects: ['Long-lasting', 'Balanced', 'Smooth'],
    description: 'Delicious fruit-flavored gummies with precise dosing.',
    images: ['/edibles/gummies-1.jpg'],
    rating: 4.7,
    reviews: 156,
    inStock: true
  },
  {
    id: 'e2',
    type: 'edible',
    name: 'Chocolate Bliss',
    category: 'Chocolate',
    thc: '5mg/square',
    pieces: '20',
    price: 'R220',
    flavors: ['Dark Chocolate', 'Sea Salt'],
    effects: ['Relaxing', 'Mild', 'Consistent'],
    description: 'Premium dark chocolate with precise micro-dosing.',
    images: ['/edibles/chocolate-1.jpg'],
    rating: 4.8,
    reviews: 134,
    inStock: true
  },
  {
    id: 'e3',
    type: 'edible',
    name: 'Baked Cookies',
    category: 'Baked',
    thc: '15mg/cookie',
    pieces: '6',
    price: 'R150',
    flavors: ['Chocolate Chip', 'Vanilla'],
    effects: ['Potent', 'Long-lasting'],
    description: 'Classic chocolate chip cookies with a twist.',
    images: ['/edibles/cookies-1.jpg'],
    rating: 4.6,
    reviews: 98,
    inStock: true
  },
  // Accessories
  {
    id: 'a1',
    type: 'accessory',
    name: 'Premium Grinder',
    category: 'Tools',
    material: 'Aircraft Aluminum',
    price: 'R350',
    features: ['4-piece', 'Kief Catcher', 'Magnetic Lid'],
    description: 'Professional-grade herb grinder with diamond-sharp teeth.',
    images: ['/accessories/grinder-1.jpg'],
    rating: 4.9,
    reviews: 203,
    inStock: true
  },
  {
    id: 'a2',
    type: 'accessory',
    name: 'Glass Bubbler',
    category: 'Glass',
    material: 'Borosilicate Glass',
    price: 'R650',
    features: ['Percolator', 'Ice Catch', 'Thick Glass'],
    description: 'Handcrafted glass bubbler for smooth hits.',
    images: ['/accessories/bubbler-1.jpg'],
    rating: 4.8,
    reviews: 167,
    inStock: true
  },
  {
    id: 'a3',
    type: 'accessory',
    name: 'Rolling Tray Set',
    category: 'Essentials',
    material: 'Bamboo',
    price: 'R280',
    features: ['Large Surface', 'Storage Compartment', 'Tool Holders'],
    description: 'Complete rolling station with all necessary tools.',
    images: ['/accessories/tray-1.jpg'],
    rating: 4.7,
    reviews: 145,
    inStock: true
  }
];